import type { RadarCandidate } from "@/lib/newTokenRadar";
import { getStorage } from "@/lib/storage";
import type { ExitSignal, SetupPerformanceStats, SetupType, TradingLabSummary, TradingPosition, TradingSetupSnapshot } from "@/lib/storage";

const DEFAULT_PAPER_NOTIONAL_USD = 10;
const PAPER_TAKE_PROFIT_PCT = 20;
const PAPER_STOP_LOSS_PCT = -15;
const PAPER_MAX_HOLD_MS = 20 * 60_000;
const MOMENTUM_EXIT_MIN_AGE_MS = 3 * 60_000;
const REENTRY_COOLDOWN_MS = 6 * 60 * 60_000;
const PAPER_ESTIMATED_ROUND_TRIP_FRICTION_PCT = 1.5; // slippage/fees proxy conservador

function pct(entry:number,current:number|null){ if(!current||entry<=0)return null; return ((current/entry)-1)*100; }
function buyRatio(c:RadarCandidate){const b=c.buysM5??0,s=c.sellsM5??0,t=b+s;return t>0?b/t:null;}
function setupType(c:RadarCandidate):SetupType{const a=c.transactionQualityScore??50,s=c.securityAssessment?.score??50;if(c.continuationScore>=75&&a>=70&&s>=70&&(c.liquidityUsd??0)>=25000)return "A_CONTINUATION";if(c.continuationScore>=60&&c.earlyMomentumScore>=80)return "B_MOMENTUM";return "C_SPECULATIVE";}
function setupSnapshot(c:RadarCandidate):TradingSetupSnapshot{return{setupType:setupType(c),classification:c.classification,earlyMomentumScore:c.earlyMomentumScore,continuationScore:c.continuationScore,transactionQualityScore:c.transactionQualityScore,securityScore:c.securityAssessment?.score??null,securityRisk:c.securityAssessment?.risk??"unknown",liquidityUsd:c.liquidityUsd,marketCapOrFdv:c.marketCapOrFdv,ageMinutes:c.ageMinutes,buyRatioM5:buyRatio(c),priceChangeM5:c.priceChangeM5,volumeM5:c.volumeM5,visibleSource:c.visibleSource};}
function qualifies(c:RadarCandidate){return Boolean(c.isLive&&c.currentStatus==="live"&&c.price&&c.price>0&&(c.classification==="breakout"||c.classification==="explosive")&&c.earlyMomentumScore>=70&&c.continuationScore>=60&&(c.transactionQualityScore??50)>=50&&(c.liquidityUsd??0)>=15000&&!c.securityAssessment?.critical&&c.activityInflationRisk!=="critical");}
function exitSignal(p:TradingPosition,c:RadarCandidate|null,now:number):{signal:ExitSignal;reason:string|null}{const ret=p.unrealizedReturnPct,age=now-new Date(p.openedAt).getTime();if(c?.securityAssessment?.critical)return{signal:"security_exit",reason:"Security Engine passou a CRITICAL"};if(ret!==null&&ret<=PAPER_STOP_LOSS_PCT)return{signal:"stop_loss",reason:`Stop experimental atingido (${ret.toFixed(1)}%)`};if(ret!==null&&ret>=PAPER_TAKE_PROFIT_PCT)return{signal:"take_profit",reason:`Take-profit experimental atingido (+${ret.toFixed(1)}%)`};if(age>=MOMENTUM_EXIT_MIN_AGE_MS&&c&&(c.currentStatus!=="live"||(c.continuationScore<45&&(c.priceChangeM5??0)<=0)))return{signal:"momentum_expired",reason:`Momentum deteriorou (Continuation ${c.continuationScore.toFixed(0)})`};if(age>=PAPER_MAX_HOLD_MS)return{signal:"time_exit",reason:"Janela experimental máxima de 20 min atingida"};if(!c&&age>=5*60_000)return{signal:"stale",reason:"Token deixou de ter dados recentes no Radar"};return{signal:"hold",reason:null};}
function createPosition(c:RadarCandidate,mode:"paper"|"manual",now:number,notional=DEFAULT_PAPER_NOTIONAL_USD):TradingPosition{const entry=c.price!;return{id:`${mode}:${c.tokenKey}:${now}`,mode,status:"open",tokenKey:c.tokenKey,chain:c.chain,address:c.address,symbol:c.symbol,name:c.name,openedAt:new Date(now).toISOString(),closedAt:null,entryPrice:entry,currentPrice:entry,exitPrice:null,notionalUsd:notional,quantityVirtual:notional/entry,realizedReturnPct:null,unrealizedReturnPct:0,peakReturnPct:0,maxDrawdownPct:0,exitSignal:"hold",exitReason:null,lastUpdatedAt:new Date(now).toISOString(),setup:setupSnapshot(c)};}
export async function syncTradingLab(allCandidates:RadarCandidate[],liveCandidates:RadarCandidate[]){const storage=getStorage(),now=Date.now(),byKey=new Map(allCandidates.map(c=>[c.tokenKey,c]));const positions=await storage.listTradingPositions();for(const p of positions.filter(x=>x.status==="open")){const c=byKey.get(p.tokenKey)??null,currentPrice=c?.price??p.currentPrice,currentReturn=pct(p.entryPrice,currentPrice);const updated:TradingPosition={...p,currentPrice,unrealizedReturnPct:currentReturn,peakReturnPct:currentReturn===null?p.peakReturnPct:Math.max(p.peakReturnPct??currentReturn,currentReturn),maxDrawdownPct:currentReturn===null?p.maxDrawdownPct:Math.min(p.maxDrawdownPct??currentReturn,currentReturn),lastUpdatedAt:new Date(now).toISOString()};const exit=exitSignal(updated,c,now);updated.exitSignal=exit.signal;updated.exitReason=exit.reason;if(p.mode==="paper"&&exit.signal!=="hold"&&currentPrice&&currentReturn!==null){updated.status="closed";updated.closedAt=new Date(now).toISOString();updated.exitPrice=currentPrice;updated.realizedReturnPct=currentReturn-PAPER_ESTIMATED_ROUND_TRIP_FRICTION_PCT;updated.unrealizedReturnPct=null;}await storage.upsertTradingPosition(updated);}const refreshed=await storage.listTradingPositions();for(const c of liveCandidates.filter(qualifies)){const recent=refreshed.some(p=>p.mode==="paper"&&p.tokenKey===c.tokenKey&&now-new Date(p.openedAt).getTime()<REENTRY_COOLDOWN_MS);if(!recent)await storage.upsertTradingPosition(createPosition(c,"paper",now));}}
export async function openManualPosition(candidate:RadarCandidate,notional=DEFAULT_PAPER_NOTIONAL_USD){if(!candidate.price||candidate.price<=0)throw new Error("Preço atual indisponível.");const p=createPosition(candidate,"manual",Date.now(),Math.max(1,Math.min(10000,notional)));await getStorage().upsertTradingPosition(p);return p;}
export async function closeManualPosition(id:string){const storage=getStorage(),p=await storage.getTradingPosition(id);if(!p||p.mode!=="manual"||p.status!=="open")throw new Error("Posição manual aberta não encontrada.");if(!p.currentPrice)throw new Error("Preço atual indisponível.");const realized=pct(p.entryPrice,p.currentPrice);const closed:TradingPosition={...p,status:"closed",closedAt:new Date().toISOString(),exitPrice:p.currentPrice,realizedReturnPct:realized,unrealizedReturnPct:null,exitSignal:"hold",exitReason:"Fechada manualmente",lastUpdatedAt:new Date().toISOString()};await storage.upsertTradingPosition(closed);return closed;}
function median(v:number[]){if(!v.length)return null;const s=[...v].sort((a,b)=>a-b),m=Math.floor(s.length/2);return s.length%2?s[m]:(s[m-1]+s[m])/2;}
function statsFor(setup:SetupType,positions:TradingPosition[]):SetupPerformanceStats{const closed=positions.filter(p=>p.mode==="paper"&&p.status==="closed"&&p.setup.setupType===setup&&p.realizedReturnPct!==null),returns=closed.map(p=>p.realizedReturnPct!),wins=returns.filter(x=>x>0),losses=returns.filter(x=>x<0),gp=wins.reduce((a,b)=>a+b,0),gl=Math.abs(losses.reduce((a,b)=>a+b,0)),hold=closed.map(p=>((p.closedAt?new Date(p.closedAt).getTime():Date.now())-new Date(p.openedAt).getTime())/60000);return{setupType:setup,sampleSize:closed.length,winRatePct:closed.length?wins.length/closed.length*100:null,medianReturnPct:median(returns),averageReturnPct:returns.length?returns.reduce((a,b)=>a+b,0)/returns.length:null,profitFactor:gl>0?gp/gl:null,averageHoldMinutes:hold.length?hold.reduce((a,b)=>a+b,0)/hold.length:null};}
export async function getTradingLabSummary():Promise<TradingLabSummary>{const positions=(await getStorage().listTradingPositions()).sort((a,b)=>new Date(b.openedAt).getTime()-new Date(a.openedAt).getTime()),paperClosed=positions.filter(p=>p.mode==="paper"&&p.status==="closed"),paperOpen=positions.filter(p=>p.mode==="paper"&&p.status==="open"),manualClosed=positions.filter(p=>p.mode==="manual"&&p.status==="closed"),manualOpen=positions.filter(p=>p.mode==="manual"&&p.status==="open"),realized=paperClosed.reduce((sum,p)=>sum+p.notionalUsd*((p.realizedReturnPct??0)/100),0),wins=paperClosed.filter(p=>(p.realizedReturnPct??0)>0).length;return{generatedAt:new Date().toISOString(),paperOpen,paperClosed:paperClosed.slice(0,100),manualOpen,manualClosed:manualClosed.slice(0,100),statsBySetup:[statsFor("A_CONTINUATION",positions),statsFor("B_MOMENTUM",positions),statsFor("C_SPECULATIVE",positions)],paperTotalRealizedUsd:realized,paperWinRatePct:paperClosed.length?wins/paperClosed.length*100:null,paperTradesClosed:paperClosed.length,defaultPaperNotionalUsd:DEFAULT_PAPER_NOTIONAL_USD};}
